site_name: AWS ML Notes
site_url: site_url
site_dir: public
docs_dir: ./wiki
theme:
  name: material
  palette:
    scheme: slate
# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
plugins:
  - search
  - roamlinks
